### ISSUE TITLE
IOC claims that there are 4 motors, but only the first works

### ISSUE THREAD

**Issue by MichaelWedel** [EuropeanSpallationSource/m-epics-IcePAP#1]
When the ioc is started and `dbl` is issued, the IOC shows that there are 4 motors. Accessing them via `caget`/`caput` works, but nothing happens in the simulator.

The simulator has to be configured to actually have 4 motors.

**Comment by tboegi** [comment]
Thanks for reporting.
The issue is fixed here:
https://github.com/EuropeanSpallationSource/m-epics-IcePAP/commit/e3bd46e04dac0bbcf1802f3a68fb211d1505624a
